### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/httpd#2]
apr-util needs libsybdb.so.5 provided by freetds but the latter is commented out in the yaml file. Is there a reason for that?

package: apr-util-freetds-1.5.4-5.module_e371b188.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libsybdb.so.5()(64bit)
package: apr-util-odbc-1.5.4-5.module_e371b188.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libodbc.so.2()(64bit)

**Comment by phracek** [comment]
@r4f4 Is this issue solved by commit http://pkgs.fedoraproject.org/cgit/modules/httpd.git/commit/?h=f26&id=495ae8e0f2a9ce1fe370620667a4332261b53d62?

Where I can find out repoclosure?

**Comment by r4f4** [comment]
@phracek So there are still some issues with this module:

package: apr-util-odbc-1.5.4-5.module_1dba4294.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libodbc.so.2()(64bit)

You need to add unixODBC to satisfy the libodbc.so.2 requirement. This package will also satisfy the following freetds deps

package: freetds-0.95.81-3.module_1dba4294.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libodbc.so.2()(64bit)
     libodbcinst.so.2()(64bit)

**Comment by hodovska** [comment]
added here: http://pkgs.fedoraproject.org/cgit/modules/httpd.git/commit/?h=f26&id=6cade5fb4e7f656d44b9dd375348087e1dd2f32a

**Comment by r4f4** [comment]
Thank you. I'm closing this issue then.
