### ISSUE TITLE
httpd is missing dependency on python2

### ISSUE THREAD

**Issue by vcrhonek** [modularity-modules/httpd#4]
`# dnf module install httpd:master/default`
Last metadata expiration check: 0:36:56 ago on Tue Oct 17 07:48:25 2017.
Error: 
 Problem: conflicting requests
  - nothing provides libpython2.7.so.1.0()(64bit) needed by mod_wsgi-4.5.15-4.module_2e0901be.x86_64

Installation of python2 module resolves the issue:
`# dnf module install python2:master/minimal`

httpd module also needs /bin/find:
/var/tmp/rpm-tmp.3Um6ov: line 13: /bin/find: No such file or directory
warning: %post(mod_nss-1.0.14-5.module_2e0901be.x86_64) scriptlet failed, exit status 127

I was able to resolve this with:
`# dnf module install platform:master/srpm-buildroot`

(But there's already dependency on platform in httpd.yaml...)

**Comment by nphilipp** [comment]
[Here's how to fix issues like this.](https://docs.pagure.org/modularity/development/building-modules/installation-dependency-issues.html)

**Comment by alexxa** [comment]
@vcrhonek I see it was fixed. If you don't have any objections, this issue should be closed. Please notice that httpd has a stream 2.4 now, not master.

**Comment by vcrhonek** [comment]
@alexxa Yes, it's fixed, the issue can be closed. Thanks!
